# Render.com deployment configuration
services:
  - type: web
    name: ai-agent-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cloud_agent_api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard for security