# Render.com deployment configuration
services:
  - type: web
    name: ai-agent-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 cloud_agent_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12